SELECT
    'BINANCE' AS exchange,
    symbol,
    price_change,
    price_change_percent,
    weighted_avg_price,
    prev_close_price,
    last_price,
    last_qty,
    bid_price,
    bid_qty,
    ask_price,
    ask_qty,
    open_price,
    high_price,
    low_price,
    volume,
    quote_volume,
    open_time,
    close_time,
    first_id,
    last_id,
    count,
    ingested_at
FROM {{ source('bronze', 'binance_ticker_24h') }}